import { z } from 'zod';
import Database from 'better-sqlite3';
import fs from 'node:fs';
import path from 'node:path';
import Handlebars from 'handlebars';

export const GenerateReportInput = z.object({
  weekOf: z.string().optional(),
  format: z.enum(['html', 'pdf', 'both']).default('html'),
  distribute: z.object({
    email: z.array(z.string()).optional(),
    slack: z.string().optional(),
  }).optional(),
});

const OUTPUT_DIR = process.env.REPORT_OUTPUT_DIR || './reports';

const TEMPLATE = `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><title>SecureFlow Report - {{weekOf}}</title>
<style>
@import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;700&family=Source+Serif+4:wght@400;600;700&display=swap');
:root{--accent:#4361ee;--danger:#e63946;--warn:#f4a261;--ok:#2a9d8f}
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:'Source Serif 4',Georgia,serif;background:#fff;color:#1a1a2e;line-height:1.6;padding:2rem;max-width:1100px;margin:0 auto}
h1,h2,h3{font-family:'JetBrains Mono',monospace}
h1{font-size:1.8rem;color:var(--accent);margin-bottom:.5rem}
h2{font-size:1.3rem;margin:2rem 0 1rem;border-bottom:2px solid var(--accent);padding-bottom:.3rem}
.subtitle{color:#666;font-size:.9rem;margin-bottom:2rem}
.verdict{font-size:1.1rem;font-weight:700;padding:1rem;border-radius:8px;margin-bottom:2rem;text-align:center;font-family:'JetBrains Mono',monospace}
.verdict.pass{background:#d4edda;color:#155724}
.verdict.fail{background:#fde8e8;color:var(--danger)}
.verdict.warn{background:#fff3cd;color:#856404}
.card{background:#f8f9fa;border-radius:8px;padding:1.5rem;margin-bottom:1.5rem;border-left:4px solid var(--accent)}
.traffic{display:flex;gap:1rem;margin-bottom:2rem}
.light{padding:1rem;border-radius:8px;flex:1;text-align:center;font-family:'JetBrains Mono',monospace}
.light.red{background:#fde8e8;border:2px solid var(--danger)}.light .count{font-size:2rem;font-weight:700;display:block}
.light.yellow{background:#fff3cd;border:2px solid var(--warn)}
.light.green{background:#d4edda;border:2px solid var(--ok)}
table{width:100%;border-collapse:collapse;margin:1rem 0;font-size:.9rem}
th{background:var(--accent);color:#fff;padding:.6rem;text-align:left;font-family:'JetBrains Mono',monospace;font-size:.8rem}
td{padding:.5rem .6rem;border-bottom:1px solid #ddd}
.footer{margin-top:3rem;padding-top:1rem;border-top:1px solid #ddd;font-size:.8rem;color:#666;text-align:center}
</style></head><body>
<h1>SecureFlow Vulnerability Report</h1>
<p class="subtitle">Week of {{weekOf}} | Generated {{generatedAt}} | ScaleFirst / BNY Fund Services</p>
<div class="verdict {{verdictClass}}">{{verdict}}</div>
<h2>Summary</h2>
<div class="traffic">
<div class="light red"><span class="count">{{critical}}</span>Critical</div>
<div class="light yellow"><span class="count">{{high}}</span>High</div>
<div class="light green"><span class="count">{{resolved}}</span>Resolved</div>
</div>
<h2>SLA Violations</h2>
<div class="card"><p><strong>{{slaViolations}}</strong> findings exceed SLA thresholds</p></div>
<h2>Fleet Status</h2>
<div class="card"><p>Active projects: <strong>{{projectCount}}</strong> | Total findings: <strong>{{totalFindings}}</strong></p></div>
<div class="footer">Generated by SecureFlow MCP v2.0 | Apache 2.0 | Confidential</div>
</body></html>`;

const compiled = Handlebars.compile(TEMPLATE);

export function generateReport(db: Database.Database) {
  return async (rawArgs: unknown) => {
    const args = GenerateReportInput.parse(rawArgs);
    const reportId = crypto.randomUUID();
    const now = new Date();
    const weekOf = args.weekOf || getISOWeek(now);
    const generatedAt = now.toISOString();

    // Get latest snapshot data
    const latestSnapshot = db.prepare('SELECT * FROM snapshots ORDER BY timestamp DESC LIMIT 1').get() as Record<string, unknown> | undefined;
    const bySeverity = latestSnapshot ? JSON.parse(latestSnapshot.by_severity as string) : {};

    // Count SLA violations
    const slaViolations = db.prepare(`
      SELECT COUNT(*) as count FROM snapshot_findings sf
      JOIN sla_config sc ON sf.severity = sc.severity
      WHERE sf.snapshot_id = ? AND sf.age_days > sc.max_age_days
    `).get(latestSnapshot?.id || '') as { count: number } | undefined;

    const critical = bySeverity.CRITICAL || 0;
    const high = bySeverity.HIGH || 0;
    const slaCount = slaViolations?.count || 0;
    const totalFindings = latestSnapshot?.total_issues || 0;

    let verdict: string, verdictClass: string;
    if (critical > 0 || slaCount > 0) { verdict = `ACTION REQUIRED: ${critical} critical findings, ${slaCount} SLA violations`; verdictClass = 'fail'; }
    else if (high > 0) { verdict = `ATTENTION: ${high} high-severity findings`; verdictClass = 'warn'; }
    else { verdict = 'ALL CLEAR: No critical findings or SLA violations'; verdictClass = 'pass'; }

    const html = compiled({ weekOf, generatedAt, verdict, verdictClass, critical, high, resolved: 0, slaViolations: slaCount, projectCount: latestSnapshot?.project_count || 0, totalFindings });

    if (!fs.existsSync(OUTPUT_DIR)) fs.mkdirSync(OUTPUT_DIR, { recursive: true });
    const htmlPath = path.join(OUTPUT_DIR, `secureflow-report-${reportId}.html`);
    fs.writeFileSync(htmlPath, html);

    const actionItems = critical + slaCount;
    db.prepare('INSERT INTO reports (id, week_of, generated_at, verdict, action_items, html_path, data_sources) VALUES (?, ?, ?, ?, ?, ?, ?)')
      .run(reportId, weekOf, generatedAt, verdict, actionItems, htmlPath, '{}');

    // Distribution
    if (args.distribute?.email?.length) {
      try {
        const nodemailer = await import('nodemailer');
        const transporter = nodemailer.default.createTransport({
          host: process.env.SMTP_HOST, port: parseInt(process.env.SMTP_PORT || '587'),
          auth: { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS },
        });
        await transporter.sendMail({
          from: process.env.SMTP_FROM || 'secureflow@company.com',
          to: args.distribute.email.join(','),
          subject: `SecureFlow Report - ${weekOf}`, html,
        });
      } catch { /* email optional */ }
    }

    if (args.distribute?.slack) {
      try {
        const axios = (await import('axios')).default;
        await axios.post(args.distribute.slack, { text: `*SecureFlow Report - ${weekOf}*\n${verdict}` });
      } catch { /* slack optional */ }
    }

    return { reportId, outputPaths: { html: htmlPath }, verdict, actionItems };
  };
}

function getISOWeek(d: Date): string {
  const date = new Date(d);
  date.setHours(0, 0, 0, 0);
  date.setDate(date.getDate() + 3 - ((date.getDay() + 6) % 7));
  const yearStart = new Date(date.getFullYear(), 0, 4);
  const weekNo = Math.ceil(((date.getTime() - yearStart.getTime()) / 86400000 + yearStart.getDay() + 1) / 7);
  return `${date.getFullYear()}-W${String(weekNo).padStart(2, '0')}`;
}
