export class McpError extends Error {
  constructor(
    public readonly code: string,
    message: string,
  ) {
    super(message);
    this.name = 'McpError';
  }
}

// Common error codes
export const ErrorCodes = {
  AUTH_ERROR: 'AUTH_ERROR',
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  UPSTREAM_UNAVAILABLE: 'UPSTREAM_UNAVAILABLE',
  SNAPSHOT_IN_PROGRESS: 'SNAPSHOT_IN_PROGRESS',
  NO_SNAPSHOTS: 'NO_SNAPSHOTS',
  DB_CORRUPTION: 'DB_CORRUPTION',
  BRANCH_NOT_ANALYZED: 'BRANCH_NOT_ANALYZED',
  POLICY_NOT_FOUND: 'POLICY_NOT_FOUND',
  ALREADY_EXEMPTED: 'ALREADY_EXEMPTED',
  EXEMPTION_NOT_FOUND: 'EXEMPTION_NOT_FOUND',
  ALREADY_EXPIRED: 'ALREADY_EXPIRED',
  INVALID_RULE: 'INVALID_RULE',
  OSV_UNAVAILABLE: 'OSV_UNAVAILABLE',
  INVALID_COORDINATES: 'INVALID_COORDINATES',
  BUILD_FAILURE: 'BUILD_FAILURE',
  SBOM_NOT_FOUND: 'SBOM_NOT_FOUND',
  SCANNER_FAILED: 'SCANNER_FAILED',
  ASSESSMENT_NOT_FOUND: 'ASSESSMENT_NOT_FOUND',
  INVALID_SBOM: 'INVALID_SBOM',
  FORMAT_UNSUPPORTED: 'FORMAT_UNSUPPORTED',
  FTS_FAILURE: 'FTS_FAILURE',
  CVE_NOT_FOUND: 'CVE_NOT_FOUND',
  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',
  TEMPLATE_ERROR: 'TEMPLATE_ERROR',
  EMAIL_FAILED: 'EMAIL_FAILED',
  SLACK_FAILED: 'SLACK_FAILED',
  RATE_LIMIT: 'RATE_LIMIT',
  TIMEOUT: 'TIMEOUT',
} as const;
